#Should the player coordinates be displayed?
display_coords = true
#Should the current biome be displayed?
display_biome = false
#Should the current in-game time be displayed?
display_time = false
#Display the in-game time in 24 hours.
time_24h = true
#Overlay's x offset
#Range: > 0
offset_x = 5
#Overlay's y offset
#Range: > 0
offset_y = 5

